SELECT * FROM City
INTO OUTFILE '/tmp/cs348/cities.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Company
INTO OUTFILE '/tmp/cs348/companies.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Job
INTO OUTFILE '/tmp/cs348/jobs.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Assets
INTO OUTFILE '/tmp/cs348/assets.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Users
INTO OUTFILE '/tmp/cs348/users.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Loans
INTO OUTFILE '/tmp/cs348/loans.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM AssetToOwner
INTO OUTFILE '/tmp/cs348/asset_to_owner.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Dependant
INTO OUTFILE '/tmp/cs348/dependants.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';

SELECT * FROM Married
INTO OUTFILE '/tmp/cs348/married.csv' 
FIELDS ENCLOSED BY '"' 
TERMINATED BY ',' 
ESCAPED BY '"' 
LINES TERMINATED BY '\n';